#!/bin/bash

clean:
	- rm nohup.out
	- make -C CentralLap clean
	- make -C Local2Round clean
	- make -C Louvain-HTTC-DPk clean
	- make -C Louvain-HTTC-DPk-plus clean
	- make -C Louvain-IntraCount clean
	- make -C Random19-HTTC-DPk clean
	- make -C Random19-HTTC-DPk-plus clean
	- make -C Random19-IntraCount clean

